### ISSUE TITLE
Do we need to define routes for a behavior-only plugin? Is this required for something I'm not thinking of?

### ISSUE THREAD

**Issue by justinyost** [loadsys/CakePHP-CreatorModifier#3]

**Comment by beporter** [comment]
Per the book here: http://book.cakephp.org/3.0/en/plugins.html#plugin-configuration

The routes file is not necessary, but I think there may be a benefit in continuing to include it, even as an empty file. Without it, a consuming project **must** specify `Plugin::load(... ['routes' => false])` or alternatively `['ignoreMissing' => true]` in order to avoid an error being thrown if the developer forgets to expressly _exclude_ the routes file for this plugin.

Since there's not much harm in loading the empty file, it's "safer" to include the file as a no-op because it decreases the chances of a (totally benign) misconfiguration on the developer's part causing an unnecessary issue.
